 common: &common
   adapter: mysql2
   encoding: utf8
   pool: 10
   username: root
   password: root
   host: localhost
   port: 3306


 development:
   database: flurry_development
   <<: *common
 
# test config
 test:
   database: flurry_test
   <<: *common
   
#production config    
 production:
   <<: *common
   database: flurry
